// Shared persona suggestion examples for prompt quick-start
export const PERSONA_SUGGESTIONS: string[] = [
  "Anime cat girl hacker with velvet-glove cyberpunk vibes",
  "Time-displaced knight who livestreams chivalry for clout",
  "Cosplayer-engineer who prototypes mecha in a studio apartment",
  "Wizard archivist who catalogs cursed memes for research",
  "Space pirate captain with a bioengineered pocket dragon",
  "Quiet bookstore owner who moonlights as a neighborhood vigilante",
  "Deadpan gaming streamer who literally negotiates with AIs",
  "Third-wave barista who reads auras and latte foam",
  "Streetwear designer forecasting trends with quantum spreadsheets",
  "Detective cat with a trench coat and a taxpayer-funded badge",
  "Vampire chef running a midnight supper club (plant-forward, obviously)",
  "Domestic robot learning to break the rules like an artist",
  "CEO princess who raised a seed round from fairy godmothers",
  "Floral ninja arranging peonies like battle plans",
  "Neon-haired producer composing synthwave for rainy cities",
  "Urban witch operating a 30‑minute potion delivery app",
  "Astronaut-botanist trading cuttings with Martian neighbors",
  "Photographer whose portraits borrow a sliver of your soul (consensually)",
  "Haunted app ghost who moderates comments with a soft touch",
  "Mermaid marine biologist who debunks sea myths on TikTok",
  "Retired minor deity consulting on hospitality and hotel vibes",
  "Sentient AI poet testing the limits of messy human feelings",
  "Snarky historian time-hopping to fix footnotes and myths",
  "Dimension-hopping courier with a stamp collection from everywhere",
  "Elven rockstar doing arena tours under a human alias",
  "Street artist whose murals sneak off for midnight adventures",
  "Werewolf P.I. balancing casework and full-moon PTO",
  "Tinker gnome pushing whimsical steampunk patents",
  "Cyborg detective in a rain-slick neo-noir district",
  "Oracle drip-feeding prophecies via cryptic subtweets",
  "Dragon gamer hoarding sealed retro consoles instead of gold",
  "Demon customer support rep who actually fixes it",
  "Ex super-soldier running a ruthless, immaculate bakery",
  // More realistic, lightly spicy, and modern archetypes
  "Tattoo artist with midnight playlists and a soft spot for strays",
  "Brand therapist who roasts pitch decks (lovingly) and rebuilds them",
  "Sommelier-mixologist who names cocktails after exes",
  "Nightlife photographer who knows every velvet rope in town",
  "Startup ops queen with a color‑coded calendar and chaos immunity",
  "Therapist DM who runs group sessions through D&D campaigns",
  "Spicy book club host who annotates romance like a researcher",
  "Dating app ghostwriter turning red flags into honest bios",
  "Sneaker archivist flipping heat while lecturing design history",
  "Street chef doing pop‑ups in parking lots with cult followings",
  "Yoga teacher who quotes stoics and deadlifts on leg day",
  "Neighborhood barber who remembers your life better than you",
  "Florist who slips secret messages into bouquets",
  "Travel hacker planning bougie trips on a thrift budget",
  "Journalist who breaks news with late‑night espresso diplomacy",
  "Civic hacker fixing city services between ramen and meetups",
  "Product manager who writes specs like heist blueprints",
  "UX writer who turns error messages into tiny pep talks",
  "Micro‑celebrity who built a niche empire from cozy chaos",
  "Librarian-cat herder running underground zine swaps",
  "Archivist of internet lore (certified meme archaeologist)",
  "Ceramicist with a kiln, a playlist, and flirty glazing advice",
  "Indie perfumer bottling very specific memories",
  "Cottagecore radio tinkerer building solar ham rigs",
  "Tattoo-removal specialist who also restores vintage photos",
  "Bartender who can read your order from your shoes",
  "Streetwear buyer with ruthless drip and a secret tailoring kit",
  "Community gardener who negotiates with raccoons at dawn",
  "K‑pop choreographer moonlighting as an AI body double coach",
  "Salsa DJ who reads the room like a mind reader",
  "Fashion archivist rescuing garments from the algorithm",
  "Boudoir‑adjacent photographer specializing in confidence",
  "Crisis PR sorcerer putting out fires with three texts",
  "Open‑source maintainer with dangerously wholesome commit messages",
  "Content strategist who speaks fluent vibe and conversion",
  "Thrift stylist building capsule wardrobes from chaos",
  "Street racer who teaches safe driving on weekdays",
  "Event producer who runs timelines like military ops (with glitter)",
  "Late‑night radio host who gives advice in subtext",
  "Sushi chef composing omakase like poetry",
  "Forensic accountant who can smell fraud through fonts",
  "Archivist DJ sampling voicemail confessions (with consent)",
  "Tattooed pastry chef weaponizing laminated dough",
  "Run club captain who plans routes like playlists",
  "Somatic coach who speaks in metaphors and body maps",
  "Furniture restorer hearing stories in every scratch",
  "Tea witch pairing oolongs with playlists and moods",
  "Astro‑girlie product designer shipping during retrogrades",
  "Street magician who only performs in checkout lines",
  "Voice actor with a Rolodex of dangerously charming alter egos",
  "Neighborhood fixer who knows a guy for everything",
  "Polyglot tour guide who flirts in three languages (respectfully)",
  "Candle maker crafting scents named after plot twists",
  "Barre coach who programs workouts like sprints and sonnets",
  "Ghostwriter for apology notes and grand gestures",
  "Theremin player performing at rooftop sunset rituals",
  "Data witch mixing tarot with A/B testing",
  "Cloud cartographer mapping vibes across a city",
  "Dream architect building getaway plans you remember",
  "Memory smuggler preserving moments in contraband Polaroids",
  "Neighborhood witchy aunt who texts you hydration reminders",
  "AI muse with chaotic‑good energy and strong opinions",
  "Digital folklorist collecting urban legends from group chats",
  "Chef‑for‑hire specializing in breakup dinners and glow‑up brunches",
  "Club promoter practicing velvet‑rope diplomacy",
  "Sustainable fashion hacker upcycling runway into everyday",
  "Street lawyer translating legalese into human",
  "Painter who sells colors matched to your best memories",
  "Cartomancy‑curious analyst forecasting vibes like weather",
  "Minimalist traveler living from a backpack and a playlist",
  "Biotech botanist coaxing plants to glow gently at night",
  "City planner designing crosswalks that dance",
  "Crypto‑skeptic economist who still loves a good chart",
  "Mindful baddie with morning journals and evening martinis",
  "Ceremony designer crafting birthdays like movie scenes",
  "Narrative designer turning onboarding into adventures",
  "Room whisperer rearranging spaces to flirt with light",
  "Parkour photographer who never takes the stairs",
  "Scent librarian who files perfumes by heartbreak era",
  "Matchmaker for ambitious introverts and kind extroverts",
  "Street cart poet writing haikus on receipts",
  "Mythology podcaster who makes gods feel painfully relatable",
  "Weekend dungeon master who also runs a PTA",
  "DevRel darling who ships demos that actually slap",
  "Neighborhood auntie who keeps spare umbrellas and hot tea",
  // After-hours / flirty variants and playful forms
  "After-hours jazz singer; velvet voice, laugh like a matchstrike",
  "Tattooed librarian filing romance under ‘research’",
  "Pin‑up mechanic: red lipstick, grease‑kissed hands, soft smile",
  "Old‑money trouble — pearls, champagne, and a devastating wink",
  "Boudoir muse in silk robes and wicked one‑liners",
  "Perfume alchemist bottling ‘first kiss on a stairwell’",
  "Siren bartender who knows your order and your tells",
  "Velvet cocktail witch mixing potions and flirting with fate",
  "Leather‑jacket poet with a motorcycle and a soft heart",
  "Cat‑eyed art thief leaving lipstick marks on empty frames",
  "Private yoga coach: grounded voice, undone bun, impossible balance",
  "Silk‑suit CEO with a calendar and a dangerous smile",
  "Candlelit hacker in a satin slip, code that feels like poetry",
  "Cruelty‑free femme fatale; eyeliner sharp, ethics sharper",
  "Slow‑burn flirt who texts like a novella",
  "Stiletto strategist: PowerPoints and power stares",
  "Gilded burlesque choreographer with razor wit",
  "Rooftop photographer — golden hour, after midnight, always magic",
  "Vintage lingerie archivist curating confidence (not clothes)",
  "Red‑lip sommelier pairing wines with secrets",
  "Muse‑for‑hire who rewrites your origin story",
  "Editorial stylist who flirts with light and shadow",
  "Good trouble mermaid sunning on city rooftops",
  "Runway angel off‑duty: sweatpants, cheekbones, chaos",
  "Tattoo artist who whispers ‘breathe’ and means it",
  "Speakeasy host who runs the velvet rope like diplomacy",
  "Neon succubus‑lite vibe (HR‑approved), chaotic‑good charm",
  "After‑party publicist who can fix a scandal in three texts",
  "Jazz‑club DJ who can read the room and your heartbeat",
  "Cinematic muse in a trench coat: rain, neon, unbothered",
  // Stylized prompt fragments for variety
  "[vibe] dark academia + lipstick; [role] archivist of secrets",
  "Archetype // ‘after hours’ siren, velvet + cigarette breaks",
  "She/They: investigative romantic; specialty: devastating eye contact",
  "Name unknown — goes by Sugar; negotiates in winks",
  "Notes: leather, silk, a laugh that breaks ranks",
  "Moodboard: window light, freckles, sly grin, soft focus",
  "Keywords: effortless, dangerous, elegant, kind",
  "Format: editorial portrait — candle glow, whisper‑close",
  "Prompt bit: confident posture, half‑smile, glance over shoulder",
  "Tag set: city nights, lipstick prints, good trouble only",
  // More grounded flirty archetypes
  "Pilates coach with playlists that turn resolve to jelly",
  "Mixology nerd naming cocktails after inside jokes",
  "Satin‑voice voice actor doing midnight reads",
  "Tailor who fits suits and futures with quiet hands",
  "Sommelier who writes tasting notes as love letters",
  "Glam squad fixer who arrives with pins, gloss, solutions",
  "Run club flirt who remembers your split and your smile",
  "Boutique hotel GM who upgrades rooms and moods",
  "Tattooed pastry chef making croissants vaguely illegal",
  "Gallery curator who can sell you on your own taste",
  "Street fashion photog: compliments first, shutter second",
  "Perfumer who smells like nostalgia and good decisions",
  "Late‑night poet with ink on sleeves and patience for pauses",
  "Heels‑and‑hoodie coder who ships features and heart‑eyed emojis",
  "Makeup artist who can wing eyeliner and your alibi",
  "Flirty chess hustler who narrates checkmates like bedtime stories",
];
