import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navigation from "@/components/layout/navigation";
import { lazy, Suspense } from "react";

const LibraryModal = lazy(() => import("@/components/library/library-modal"));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-[var(--navigation-height)]`}
      >
        <Providers>
          <Navigation />

          {children}

          <Suspense fallback={null}>
            <LibraryModal />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
