
name: Build App

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNKEY_ROOT_KEY: dummy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
      - run: pnpm install
      - run: pnpm build